version: "2.0"
services:
    zenserver:
        build:
            context: ./
            dockerfile: arm.dockerfile
        ports:
            - "5000:5000"
    mosquitto:
        image: eclipse-mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"



